[package]
name = "light_sensor"
version = "0.1.0"
authors = ["kaisawind <wind.kaisa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5.4"
i2cdev = "0.4.4"
